import React, { Component } from "react";

class LabFacility extends Component {
  state = {};
  render() {
    return (
      <>
        <h2 className="director-heading">Lab Facility</h2>
        <div className="facility-page-image-container">
          <div className="facility-page-image-1"></div>
          <div className="facility-page-image-2-container">
            <div className="facility-page-image-2"></div>
            <div className="facility-page-image-2"></div>
          </div>
        </div>
        <div className="director-page-main-content">
          <p>
            <b>The Department of Electronics and Communication</b> comprises of
            12 fully equipped labs. The students have easy access to CRO, power
            supplies, function generator, trainer kits as well as relevant
            analog and digital IC in the following labs:
            <ul>
              <li>Analog Electronics</li> <li>Digital Electronics</li>
              <li>Microwave Engg.</li>
              <li> Circuits and Systems</li>
              <li>Electrical Science Communication</li>
              <li> Systems Telecommunication Systems</li>
            </ul>
          </p>
          <p>
            Emphasis is given for circuit designing on the bread board.
            <br /> The other labs. of the department are :
          </p>
          <p>
            <b>Microprocessor Lab:</b>
            <br />
            It is devoted to programming of 8085 and 8086 microprocessor using
            Trainer kits with assembler as well as interfacing cards like 8251,
            8253, 8255, 8257, 8259, 8279, ADC, DAC etc. Two sets of 8086 based
            In-circuit Emulators are there to develop projects on mp. The
            sophisticated mixed scale OSC of 60MHz with logic Analyser is
            available for checking different signals generated by
            microprocessor.
          </p>
          <p>
            <b>
              Consumer Electronics and Satellite and Mobile Communication Lab:
            </b>
            <br />
            This is an advanced specialized lab. consisting of trainer kits in
            the area of Mobile Comm., GPS, Satellite Comm., CDMA Cassette tape
            Recorder.
          </p>
          <p>
            <b>Embedded Systems:</b>
            <br />
            This emerging scientific enterprise called "Embedded Systems" is all
            set to open new horizons for the students of this field. A new lab
            has been set up in the college for this very purpose, thus taking a
            bold step in enlightening students in till now unventured areas in
            embedded technology.
          </p>
          <p>
            Here, we have 2 platforms to develop embedded systems which are:
          </p>
          <ul style={{ listStyle: "none" }}>
            <li>
              1) Intel 8051 based target board with cross-compiler and an
              IN-SYSTEM PROGRAMMER for storing the program from PC to the
              microcontroller. Along with that, there are certain interfacing
              resources available with the target board such as LCD, Keypad, 7
              segment display, ADC, DAC, stepper motor, RTC etc.
            </li>
            <br />
            <li>
              2) The second target board contains microchips PIC 16X controller
              with IDE of MP LAB for writing the program and storing it on the
              microcontroller. There is also a universal programmer available to
              program the microcontroller and program memories. Addition systems
              include the microprocessor development system with in circuit
              emulator for 8085 and 8031 based PODS.
            </li>
          </ul>
          <p className="director-page-main-content-designation"></p>
        </div>
      </>
    );
  }
}

export default LabFacility;
