import Banner1 from "./assets/images/banner-1_.jpg";
import Microsoft from "./assets/images/microsoft.jpg";
import Banner2 from "./assets/images/banner-2.jpg";
import Banner3 from "./assets/images/banner-3.jpg";
import Banner4 from "./assets/images/banner-4.jpg";
import Banner5 from "./assets/images/banner-6.jpg";
import Banner6 from "./assets/images/banner-7.jpg";
import Banner7 from "./assets/images/banner-8.jpg";
import Banner8 from "./assets/images/banner-10.jpg";
import Banner9 from "./assets/images/banner-11.jpg";
import Banner10 from "./assets/images/banner-12.jpg";
import Banner11 from "./assets/images/banner-13.jpg";
import Banner12 from "./assets/images/banner-14.jpg";
import Banner13 from "./assets/images/banner-15.jpg";
import Banner14 from "./assets/images/banner-1.jpg";
import Banner20 from "./assets/images/banner-20.jpeg";
import Banner21 from "./assets/images/banner-21.jpeg";
import Banner22 from "./assets/images/banner-22.jpeg";
import Banner23 from "./assets/images/banner-23.jpeg";

export const carousel = [
  { image: Banner1 },
  { image: Banner2 },
  { image: Banner3 },
  { image: Microsoft },
  { image: Banner5 },
  { image: Banner6 },
  { image: Banner7 },
  { image: Banner8 },
  { image: Banner9 },
  { image: Banner10 },
  { image: Banner11 },
  { image: Banner12 },
  { image: Banner4 },
  { image: Banner13 },
  { image: Banner20 },
  { image: Banner21 },
  { image: Banner22 },
  { image: Banner23 },
  { image: Banner14 },
];
